In [1]:
import pandas as pd
import os
import glob
import io
import requests
import ssl
from sklearn import preprocessing
from sklearn.utils import shuffle

In [2]:
# dir paths
CONVERTED_DATA = '../data/data_converted'
PROCESSED_DATA = '../data/processed'

# Converted datastest
path_converted = os.path.abspath(CONVERTED_DATA)
csv_files_converted = glob.glob(os.path.join(path_converted, '*.csv'))
print(path_converted)
print(csv_files_converted)

# processed data sets
path_processed = os.path.abspath(PROCESSED_DATA)
csv_files_processed = glob.glob(os.path.join(path_processed, '*.csv'))
print(path_processed)
print(csv_files_processed)

/home/rusty/fun/Master-Thesis/data/data_converted
['/home/rusty/fun/Master-Thesis/data/data_converted/borovecki.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/subramanian.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/burczynski.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/sorlie.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/khan.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/singh.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/tian.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/chiaretti.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/christensen.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/chin.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/su.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/shipp.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/nakayama.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/alon.csv', '/home/rusty/fun/Master-Thesis/data/data_conv

In [3]:
df_conv = pd.read_csv(csv_files_converted[0])
df_conv.head()

data  label
0  0.368080      1
1  0.726225      0
2  0.212942      0
3  0.427461      0
4  0.596491      1

In [4]:
df_pros = pd.read_csv(csv_files_processed[4])
df_pros.head()

x.GENE1   x.GENE2   x.GENE3   x.GENE4   x.GENE5   x.GENE6   x.GENE7  \
0  0.773344 -2.438405 -0.482562 -2.721135 -1.217058  0.827809  1.342604   
1 -0.078178 -2.415754  0.412772 -2.825146 -0.626236  0.054488  1.429498   
2 -0.084469 -1.649739 -0.241308 -2.875286 -0.889405 -0.027474  1.159300   
3  0.965614 -2.380547  0.625297 -1.741256 -0.845366  0.949687  1.093801   
4  0.075664 -1.728785  0.852626  0.272695 -1.841370  0.327936  1.251219   

    x.GENE8   x.GENE9  x.GENE10  ...  x.GENE2300  x.GENE2301  x.GENE2302  \
0  0.057042  0.133569  0.565427  ...   -0.027474   -1.660205    0.588231   
1 -0.120249  0.456792  0.159053  ...   -0.246284   -0.836325   -0.571284   
2  0.015676  0.191942  0.496585  ...    0.024985   -1.059872   -0.403767   
3  0.819736 -0.284620  0.994732  ...    0.357115   -1.893128    0.255107   
4  0.771450  0.030917  0.278313  ...    0.061753   -2.273998   -0.039365   

   x.GENE2303  x.GENE2304  x.GENE2305  x.GENE2306  x.GENE2307  x.GENE2308    y  
0   -0.463624   -3.952845   -5.496768   -1.414282   -0.647600   -1.763172  EWS  
1    0.034788   -2.478130   -3.661264   -1.093923   -1.209320   -0.824395  EWS  
2   -0.678653   -2.939352   -2.736450   -1.965399   -0.805868   -1.139434  EWS  
3    0.163309   -1.021929   -2.077843   -1.127629    0.331531   -2.179483  EWS  
4    0.368801   -2.566551   -1.675044   -1.082050   -0.965218   -1.836966  EWS  

[5 rows x 2309 columns]

In [5]:
def prepare_dataset_for_modeling_plane(dataset_name,
                                 pred_type,
                                 data_directory=None,
                                 na_values='?',
                                 n_samples_max=None,
                                 random_state=999,
                                 drop_const_columns=True,
                                 scale_data=True):


    if pred_type not in ['c', 'r']:
        raise ValueError("Prediction type needs to be either 'c' for classification or 'r' for regression.")

    if data_directory:
        # read in from local directory
        df = pd.read_csv(data_directory + dataset_name, na_values=na_values, header=0)
        print(f'DATA: {df.head()}')
    else:
        # read in the data file from GitHub into a Pandas data frame
        if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
                getattr(ssl, '_create_unverified_context', None)):
            ssl._create_default_https_context = ssl._create_unverified_context
        github_location = 'https://raw.githubusercontent.com/vaksakalli/datasets/master/'
        dataset_url = github_location + dataset_name.lower()
        df = pd.read_csv(io.StringIO(requests.get(dataset_url).content.decode('utf-8')), na_values=na_values, header=0)

    # drop missing values before (any) sampling
    df = df.dropna()

    n_observations = df.shape[0]  # no. of observations in the dataset
    n_samples = n_observations  # initialization - no. of observations after (any) sampling
    if n_samples_max and (n_samples_max < n_observations):
        # do not sample more rows than what is in the dataset
        n_samples = n_samples_max
    df = shuffle(df, n_samples=n_samples, random_state=random_state)

    if drop_const_columns:
        df = df.loc[:, df.nunique() > 1]
    df = df.drop_duplicates(ignore_index=True)

    y = df.iloc[:, -1].values
    x = df.iloc[:, :-1]

    categorical_cols = x.columns[x.dtypes == object].tolist()

    print(f'\nnumber of nominal categorical descriptive features detected: {len(categorical_cols)}\n')

    for col in categorical_cols:
        n = len(x[col].unique())
        if n == 2:
            x[col] = pd.get_dummies(x[col], drop_first=True)
    x = pd.get_dummies(x).values

    if scale_data:
        x = preprocessing.MinMaxScaler().fit_transform(x)
        if pred_type == 'r':
            y = preprocessing.MinMaxScaler().fit_transform(y.reshape(-1, 1)).flatten()

    if pred_type == 'c':
        y = preprocessing.LabelEncoder().fit_transform(y)

    return x, y

In [6]:
cc = pd.read_csv(csv_files_processed[4])
cc.head()

x.GENE1   x.GENE2   x.GENE3   x.GENE4   x.GENE5   x.GENE6   x.GENE7  \
0  0.773344 -2.438405 -0.482562 -2.721135 -1.217058  0.827809  1.342604   
1 -0.078178 -2.415754  0.412772 -2.825146 -0.626236  0.054488  1.429498   
2 -0.084469 -1.649739 -0.241308 -2.875286 -0.889405 -0.027474  1.159300   
3  0.965614 -2.380547  0.625297 -1.741256 -0.845366  0.949687  1.093801   
4  0.075664 -1.728785  0.852626  0.272695 -1.841370  0.327936  1.251219   

    x.GENE8   x.GENE9  x.GENE10  ...  x.GENE2300  x.GENE2301  x.GENE2302  \
0  0.057042  0.133569  0.565427  ...   -0.027474   -1.660205    0.588231   
1 -0.120249  0.456792  0.159053  ...   -0.246284   -0.836325   -0.571284   
2  0.015676  0.191942  0.496585  ...    0.024985   -1.059872   -0.403767   
3  0.819736 -0.284620  0.994732  ...    0.357115   -1.893128    0.255107   
4  0.771450  0.030917  0.278313  ...    0.061753   -2.273998   -0.039365   

   x.GENE2303  x.GENE2304  x.GENE2305  x.GENE2306  x.GENE2307  x.GENE2308    y  
0   -0.463624   -3.952845   -5.496768   -1.414282   -0.647600   -1.763172  EWS  
1    0.034788   -2.478130   -3.661264   -1.093923   -1.209320   -0.824395  EWS  
2   -0.678653   -2.939352   -2.736450   -1.965399   -0.805868   -1.139434  EWS  
3    0.163309   -1.021929   -2.077843   -1.127629    0.331531   -2.179483  EWS  
4    0.368801   -2.566551   -1.675044   -1.082050   -0.965218   -1.836966  EWS  

[5 rows x 2309 columns]

In [7]:
# dir paths
CONVERTED_DATA = '../data/data_converted'
PROCESSED_DATA = '../data/processed'

# Converted datastest
path_converted = os.path.abspath(CONVERTED_DATA)
csv_files_converted = glob.glob(os.path.join(path_converted, '*.csv'))
print(path_converted)
print(csv_files_converted)

# processed data sets
path_processed = os.path.abspath(PROCESSED_DATA)
csv_files_processed = glob.glob(os.path.join(path_processed, '*.csv'))
print(path_processed)
print(csv_files_processed)

def prepare_dataset_for_modeling(dataset_name,
                                 pred_type,
                                 data_directory=None,
                                 na_values='?',
                                 n_samples_max=None,
                                 random_state=999,
                                 drop_const_columns=True,
                                 scale_data=True):

    print(f'DATASET NAME: {dataset_name}')
    print(f'directory path: {data_directory}')

    if pred_type not in ['c', 'r']:
        raise ValueError("Prediction type needs to be either 'c' for classification or 'r' for regression.")

    if data_directory:
        if not data_directory.endswith('/'):
            data_directory += '/'
        df = pd.read_csv(data_directory + dataset_name, na_values=na_values, header=0)
        print(f'DATA: {df.head()}')
    print(f'DF LEN BEFORE DROP NA: {len(df)}')
    df = df.dropna()
    print(f'DF AFTER DROP NA: {len(df)}')

    n_observations = df.shape[0]  # no. of observations in the dataset
    n_samples = n_observations  # initialization - no. of observations after (any) sampling
    if n_samples_max and (n_samples_max < n_observations):
        # do not sample more rows than what is in the dataset
        n_samples = n_samples_max
    df = shuffle(df, n_samples=n_samples, random_state=random_state)

    if drop_const_columns:
        df = df.loc[:, df.nunique() > 1]
    df = df.drop_duplicates(ignore_index=True)

    y = df.iloc[:, -1].values
    x = df.iloc[:, :-1]

    categorical_cols = x.columns[x.dtypes == object].tolist()

    print(f'\nnumber of nominal categorical descriptive features detected: {len(categorical_cols)}\n')

    for col in categorical_cols:
        n = len(x[col].unique())
        if n == 2:
            x[col] = pd.get_dummies(x[col], drop_first=True)
    x = pd.get_dummies(x).values

    if scale_data:
        x = preprocessing.MinMaxScaler().fit_transform(x)
        if pred_type == 'r':
            y = preprocessing.MinMaxScaler().fit_transform(y.reshape(-1, 1)).flatten()

    if pred_type == 'c':
        y = preprocessing.LabelEncoder().fit_transform(y)

    return x, y

dataset_name = os.path.basename(csv_files_processed[4])  # Extract the dataset name from the file path
data_directory = os.path.dirname(csv_files_processed[4]) 

x, y = prepare_dataset_for_modeling(dataset_name, pred_type='c', data_directory=data_directory)

print(f'X : {x}')
print(f'Y : {y}')
test_df_x = pd.DataFrame(x)
test_df_y = pd.DataFrame(y)

/home/rusty/fun/Master-Thesis/data/data_converted
['/home/rusty/fun/Master-Thesis/data/data_converted/borovecki.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/subramanian.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/burczynski.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/sorlie.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/khan.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/singh.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/tian.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/chiaretti.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/christensen.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/chin.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/su.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/shipp.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/nakayama.csv', '/home/rusty/fun/Master-Thesis/data/data_converted/alon.csv', '/home/rusty/fun/Master-Thesis/data/data_conv

In [8]:
test_df_x.head()

0         1         2         3         4         5         6     \
0  0.860841  0.796585  0.434166  0.072852  0.961813  0.488233  0.296081   
1  0.107140  0.190904  0.135591  0.900945  0.486763  0.304533  0.362354   
2  0.861976  0.532713  0.022876  0.383588  0.748794  0.645816  0.180995   
3  0.727536  0.263340  0.696222  0.867443  0.364803  0.467848  0.303109   
4  0.736457  0.612572  0.592135  0.075775  0.773278  0.644309  0.380658   

       7         8         9     ...      2298      2299      2300      2301  \
0  0.670272  0.524320  0.875058  ...  0.856483  0.627220  0.437818  0.630889   
1  0.372306  0.756917  0.723061  ...  0.000000  0.564739  0.664596  0.303845   
2  0.713352  0.291189  0.493789  ...  0.864783  0.383464  0.439293  0.418139   
3  0.622896  1.000000  0.685706  ...  0.522840  0.169435  0.720511  0.533016   
4  0.754610  0.577157  0.757996  ...  0.723895  0.572220  0.521391  0.920097   

       2302      2303      2304      2305      2306      2307  
0  0.112992  0.667834  0.607790  0.630719  0.946783  0.574710  
1  0.028926  0.573100  0.910751  0.633459  0.728358  0.566102  
2  0.769302  0.701675  0.688168  0.747119  0.707713  0.721908  
3  0.784800  0.855902  0.866603  0.492418  0.700157  0.389735  
4  0.215299  0.643051  0.545423  0.420247  0.839062  0.464071  

[5 rows x 2308 columns]

In [9]:
test_df_y.head()

0
0  3
1  0
2  3
3  2
4  3

In [10]:
result = pd.concat([test_df_x, test_df_y.rename(columns={0: 'label'})], axis=1)
result.head()

0         1         2         3         4         5         6  \
0  0.860841  0.796585  0.434166  0.072852  0.961813  0.488233  0.296081   
1  0.107140  0.190904  0.135591  0.900945  0.486763  0.304533  0.362354   
2  0.861976  0.532713  0.022876  0.383588  0.748794  0.645816  0.180995   
3  0.727536  0.263340  0.696222  0.867443  0.364803  0.467848  0.303109   
4  0.736457  0.612572  0.592135  0.075775  0.773278  0.644309  0.380658   

          7         8         9  ...      2299      2300      2301      2302  \
0  0.670272  0.524320  0.875058  ...  0.627220  0.437818  0.630889  0.112992   
1  0.372306  0.756917  0.723061  ...  0.564739  0.664596  0.303845  0.028926   
2  0.713352  0.291189  0.493789  ...  0.383464  0.439293  0.418139  0.769302   
3  0.622896  1.000000  0.685706  ...  0.169435  0.720511  0.533016  0.784800   
4  0.754610  0.577157  0.757996  ...  0.572220  0.521391  0.920097  0.215299   

       2303      2304      2305      2306      2307  label  
0  0.667834  0.607790  0.630719  0.946783  0.574710      3  
1  0.573100  0.910751  0.633459  0.728358  0.566102      0  
2  0.701675  0.688168  0.747119  0.707713  0.721908      3  
3  0.855902  0.866603  0.492418  0.700157  0.389735      2  
4  0.643051  0.545423  0.420247  0.839062  0.464071      3  

[5 rows x 2309 columns]

In [11]:
irsis_b = pd.read_csv('iris.csv')
irsis_b.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [12]:
def prepare_dataset(dataset_name,
                                 pred_type,
                                 data_directory=None,
                                 na_values='?',
                                 n_samples_max=None,
                                 random_state=999,
                                 drop_const_columns=True,
                                 scale_data=True):

    print(f'DATASET NAME: {dataset_name}')
    print(f'directory path: {data_directory}')

    if pred_type not in ['c', 'r']:
        raise ValueError("Prediction type needs to be either 'c' for classification or 'r' for regression.")

    if data_directory:
        if not data_directory.endswith('/'):
            data_directory += '/'
        df = pd.read_csv(data_directory + dataset_name, na_values=na_values, header=0)
        print(f'DATA: {df.head()}')
    else:
        df = pd.read_csv(dataset_name)
    print(f'DF LEN BEFORE DROP NA: {len(df)}')
    df = df.dropna()
    print(f'DF AFTER DROP NA: {len(df)}')

    n_observations = df.shape[0]  # no. of observations in the dataset
    n_samples = n_observations  # initialization - no. of observations after (any) sampling
    if n_samples_max and (n_samples_max < n_observations):
        # do not sample more rows than what is in the dataset
        n_samples = n_samples_max
    df = shuffle(df, n_samples=n_samples, random_state=random_state)

    if drop_const_columns:
        df = df.loc[:, df.nunique() > 1]
    df = df.drop_duplicates(ignore_index=True)

    y = df.iloc[:, -1].values
    x = df.iloc[:, :-1]

    categorical_cols = x.columns[x.dtypes == object].tolist()

    print(f'\nnumber of nominal categorical descriptive features detected: {len(categorical_cols)}\n')

    for col in categorical_cols:
        n = len(x[col].unique())
        if n == 2:
            x[col] = pd.get_dummies(x[col], drop_first=True)
    x = pd.get_dummies(x).values

    if scale_data:
        x = preprocessing.MinMaxScaler().fit_transform(x)
        if pred_type == 'r':
            y = preprocessing.MinMaxScaler().fit_transform(y.reshape(-1, 1)).flatten()

    if pred_type == 'c':
        y = preprocessing.LabelEncoder().fit_transform(y)

    return x, y

In [13]:
x, y = prepare_dataset('iris.csv', pred_type='c')
print(f'X : {x}')
print(f'Y : {y}')

DATASET NAME: iris.csv
directory path: None
DF LEN BEFORE DROP NA: 150
DF AFTER DROP NA: 150

number of nominal categorical descriptive features detected: 0

X : [[0.44444444 0.41666667 0.54237288 0.58333333]
 [0.36111111 0.375      0.44067797 0.5       ]
 [0.33333333 0.16666667 0.47457627 0.41666667]
 [0.19444444 0.625      0.05084746 0.08333333]
 [0.33333333 0.625      0.05084746 0.04166667]
 [0.22222222 0.625      0.06779661 0.04166667]
 [0.22222222 0.75       0.15254237 0.125     ]
 [0.41666667 0.29166667 0.49152542 0.45833333]
 [0.52777778 0.33333333 0.6440678  0.70833333]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.19444444 0.58333333 0.10169492 0.125     ]
 [0.69444444 0.5        0.83050847 0.91666667]
 [0.25       0.58333333 0.06779661 0.04166667]
 [0.5        0.25       0.77966102 0.54166667]
 [0.19444444 0.         0.42372881 0.375     ]
 [0.61111111 0.41666667 0.81355932 0.875     ]
 [0.44444444 0.41666667 0.69491525 0.70833333]
 [0.58333333 0.29166667 0.72881356 0.75

In [17]:
khan = pd.read_csv('khan.csv')
khan.head(25)

x.GENE1   x.GENE2   x.GENE3   x.GENE4   x.GENE5   x.GENE6   x.GENE7  \
0   0.773344 -2.438405 -0.482562 -2.721135 -1.217058  0.827809  1.342604   
1  -0.078178 -2.415754  0.412772 -2.825146 -0.626236  0.054488  1.429498   
2  -0.084469 -1.649739 -0.241308 -2.875286 -0.889405 -0.027474  1.159300   
3   0.965614 -2.380547  0.625297 -1.741256 -0.845366  0.949687  1.093801   
4   0.075664 -1.728785  0.852626  0.272695 -1.841370  0.327936  1.251219   
5   0.458816 -2.875286  0.135841  0.405398 -2.082647  0.137847  1.733530   
6   0.067098 -1.624044  0.519627  0.238229 -1.397558  0.138805  1.825291   
7   0.094128 -1.795165  0.702751  0.206038 -1.868209  0.288182  1.406072   
8   0.108316 -1.944911  0.600099 -0.051083 -1.981952  0.119204  1.849116   
9  -0.970747 -2.347582 -0.392006 -0.141218 -1.823250 -0.303540  1.498551   
10  1.163932 -2.686778  0.044973 -2.085057 -0.705017  1.138057  1.311194   
11  0.503620 -2.645075  0.040086 -2.956512 -1.587187  0.770525  0.894127   
12  1.187203 -2.154165 -0.113617 -2.288682 -1.266558  0.681732  1.181420   
13  0.005982 -1.657578 -0.843505 -2.268184 -1.209320  0.519032  1.773273   
14  0.996875 -1.440962 -0.996146 -1.518684 -0.991284  0.576613  1.174832   
15  0.722123 -2.497384 -0.103030 -2.049494 -0.926089  0.542266  0.776063   
16  0.614266 -2.092324 -0.001701 -1.512765 -0.976572  0.562526  1.226155   
17  0.998424 -1.712025 -0.700373 -1.382701 -0.743599  1.178932  1.908772   
18  0.856753 -2.535779 -0.272596 -1.677717 -0.875389  1.037410  1.603541   
19  0.657054 -1.378326 -0.554255 -1.998046 -1.089752  0.953008  2.002925   
20  1.285507 -2.248097 -0.539054 -1.274395 -0.809232  1.111825  1.442060   
21  0.765933 -2.337177 -0.694748 -1.508688 -0.776094  1.110244  1.865227   
22  0.838243 -1.833207 -0.547144 -0.680823 -0.786579  2.452728  2.374962   
23  0.313496 -1.797576 -0.316630  0.355714 -2.126114  0.298028  1.909557   
24  0.737642 -1.056703 -1.782602 -1.598498 -1.006215  1.187996  1.153984   

     x.GENE8   x.GENE9  x.GENE10  ...  x.GENE2300  x.GENE2301  x.GENE2302  \
0   0.057042  0.133569  0.565427  ...   -0.027474   -1.660205    0.588231   
1  -0.120249  0.456792  0.159053  ...   -0.246284   -0.836325   -0.571284   
2   0.015676  0.191942  0.496585  ...    0.024985   -1.059872   -0.403767   
3   0.819736 -0.284620  0.994732  ...    0.357115   -1.893128    0.255107   
4   0.771450  0.030917  0.278313  ...    0.061753   -2.273998   -0.039365   
5   0.396424  0.045833  0.352064  ...   -1.102018   -1.545994   -0.657780   
6  -0.305439 -0.052873 -1.242367  ...    0.031596   -1.713133   -0.731680   
7   0.760338 -0.039053  0.136103  ...    0.093126   -2.269150   -0.077853   
8   0.237520 -0.050346 -0.252701  ...   -0.408119   -2.422495   -0.263835   
9  -0.206409  0.144793 -1.572142  ...   -0.226148   -2.302585    0.235862   
10  0.610635  0.231667  1.064745  ...    0.511565   -1.901798   -0.368458   
11  0.137411 -0.305032  0.692597  ...    1.281323   -1.188099    0.585395   
12  0.344015 -0.046253  0.731165  ...    0.415547   -1.434645   -0.136966   
13 -1.218072 -0.303676  0.507420  ...    0.027810   -2.254748   -0.574120   
14 -0.390232 -0.157122 -0.384487  ...   -0.517347   -2.649310   -0.916041   
15  0.445263 -0.418398  0.407995  ...    0.310055   -2.847312   -0.256571   
16  0.785362  0.052403  0.474307  ...   -0.163107   -1.583770   -1.120858   
17 -0.287282 -0.287815  0.043634  ...   -0.010050   -1.387495   -0.164521   
18 -0.400179  0.060531 -0.010050  ...    0.610472   -2.209095   -0.214432   
19  0.304244  0.569340  0.351150  ...   -0.535289   -1.860467   -1.126703   
20  0.956626 -0.001601  0.694197  ...   -0.704410   -2.399096   -1.036765   
21 -0.197232  0.079366 -0.128174  ...   -1.277619   -2.609110   -0.633747   
22  0.257197 -0.503354 -0.020509  ...   -0.101368   -0.811931   -0.316356   
23  0.170839  0.145225 -0.133303  ...   -0.962596   -1.736136   -0.517347   
24  0.333253 -0.087411 -0.241562  ...   -0.881406   -1.504177   -0.980030   

    x.GENE2303  x.GENE230

In [19]:
khan['y'].unique()

array(['EWS', 'RMS', 'NB', 'BL'], dtype=object)